-- MySQL Script generated by MySQL Workbench
-- Tue Jul  6 12:01:00 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema qcm_website
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema qcm_website
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qcm_website` DEFAULT CHARACTER SET utf8 ;
USE `qcm_website` ;

-- -----------------------------------------------------
-- Table `qcm_website`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qcm_website`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(32) NULL,
  `password` LONGTEXT NOT NULL,
  `author` BINARY NULL DEFAULT 0,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(16) NULL,
  `first_name` VARCHAR(16) NULL,
  `roles` JSON NULL,
  PRIMARY KEY (`id_user`));


-- -----------------------------------------------------
-- Table `qcm_website`.`qcm_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qcm_website`.`qcm_table` (
  `id_qcm` INT NULL AUTO_INCREMENT,
  `title_movie` VARCHAR(64) NOT NULL,
  `poster_movie` VARCHAR(128) NULL,
  `date_at` DATETIME NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_qcm`),
  INDEX `fk_qcm_table_user1_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_qcm_table_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `qcm_website`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qcm_website`.`question_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qcm_website`.`question_table` (
  `id_qestion` INT NULL AUTO_INCREMENT,
  `question` VARCHAR(128) NOT NULL,
  `reply1` VARCHAR(128) NOT NULL,
  `reply2` VARCHAR(128) NOT NULL,
  `reply3` VARCHAR(128) NOT NULL,
  `reply4` VARCHAR(128) NOT NULL,
  `good_reply` VARCHAR(128) NOT NULL,
  `qcm_table_id_qcm` INT NOT NULL,
  PRIMARY KEY (`id_qestion`),
  INDEX `fk_question_table_qcm_table1_idx` (`qcm_table_id_qcm` ASC),
  CONSTRAINT `fk_question_table_qcm_table1`
    FOREIGN KEY (`qcm_table_id_qcm`)
    REFERENCES `qcm_website`.`qcm_table` (`id_qcm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qcm_website`.`user_qcm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qcm_website`.`user_qcm` (
  `id_result` INT NULL AUTO_INCREMENT,
  `title_movie` VARCHAR(32) NOT NULL,
  `reply1` BINARY NOT NULL DEFAULT 0,
  `reply2` BINARY NOT NULL DEFAULT 0,
  `reply3` BINARY NOT NULL DEFAULT 0,
  `reply4` BINARY NOT NULL DEFAULT 0,
  `score_qcm` INT NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_result`),
  INDEX `fk_user_qcm_user1_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_user_qcm_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `qcm_website`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
